Add new policy resources per DataDog docs
cloudposse/terraform-aws-datadog-integration pull request #67
Opened 2024-10-24 23:13 UTC by StealthBadger747

## what

- Added new resources per datadog docs
  - [AWS resource collection IAM policy](https://docs.datadoghq.com/integrations/amazon_web_services/#aws-resource-collection-iam-policy provides for new resources
  - [AWS integration IAM policy](https://docs.datadoghq.com/integrations/amazon_web_services/?tab=roledelegation#aws-integration-iam-policy) - New resources for the integration

## why

I saw the following on my DataDog AWS Integration page:

<img width="522" alt="Screenshot 2024-10-24 at 4 13 20 PM" src="https://github.com/user-attachments/assets/d15a14df-4fdf-476b-989f-9beb52e694d8">

2024-10-24 23:43 UTC, StealthBadger747 commented
/terratest

2024-10-25 23:03 UTC, joe-niland requested changes
Thanks @StealthBadger747 - just a few small things

2024-10-25 23:03 UTC, joe-niland commented on iam_policy_all.tf
> +
To be consistent, it would be good to have the below in `iam_policy_resource-collection.tf`

2024-10-25 23:03 UTC, joe-niland commented on iam_policy_all.tf
> +  resource_collection_count = local.enabled && contains(local.integrations, "resource_collection") ? 1 : 0
Should also move to `iam_policy_resource-collection.tf`

2024-10-28 13:13 UTC, RoseSecurity commented
@joe-niland Do you think it would be appropriate to parameterize these permissions so that users can add permissions as needed for their environments instead of having hardcoded lists that need updating? Could be a similar pattern to providing a base set of permissions that can be added to per environment as needed

2024-10-30 07:09 UTC, Nuru commented on iam_policy_all.tf
> +  role       = aws_iam_role.default[0].name
@joe-niland The new standard is

```suggestion
  role       = one(aws_iam_role.default[*].name)
```

2024-10-30 08:27 UTC, Nuru commented
@StealthBadger747 Thank you for this PR. It appears Datadog has made several changes/updates and we need to make some more significant changes. This will become a Major release, although I would like it to not have any breaking changes anyway.

If you are up for it, please change as follows (and if you are not up for it, no problem, we will get to it eventually, but probably not soon, or maybe @RoseSecurity will want to do it):

[ ] Style update: change all `join("", resource.kind.*.name)` and `resource.kind[0].name` to `one(resource.kind[*].name)` (unless there could be more than one, of course).

[ ] Deprecate `var.integrations` and add `var.policies` in its place. 

To deprecate `var.integrations`:
1. Update the description to indicate it is deprecated
2. Make its default value null

To add `var.policies` 

```hcl
variable "policies" {
  type        = list(string)
  description = <<-EOT
    List of Datadog's names for AWS IAM policies names to apply to the role.
    Valid options are "core-integration", "full-integration", "resource-collection", "CSMP", "SecurityAudit", "everything".
    "CSMP" is for Cloud Security Posture Management, which also requires "full-integration".
    "SecurityAudit" is for the AWS-managed `SecurityAudit` Policy. 
    "everything" means all permissions for offerings.
    EOT
}
```

Create a `local.policies` which is the list of policies specified via `var.integrations` and `var.policies` combined with mappings and then de-duplicated.

For compatibility, map `var.integrations` "core" -> "core_integration" and "all" -> "full_integration" when adding to `local.policies`. 

Consider "CSMP" an alias for "SecurityAudit". 

[ ] Rename the "all" policy "full-integration" and update it.

Rename `iam_policy_all.tf` -> `iam-policy-full-integration.tf` and rename all the resources etc. named "all" to "full_integration", and trigger it with policy name  "full-integration". 

Update [the policy reference](https://github.com/cloudposse/terraform-aws-datadog-integration/blob/d8b85a3a0484456022ae8a08c4ca8786cc64e40e/iam_policy_all.tf#L1) to 

```
https://docs.datadoghq.com/integrations/amazon_web_services/?tab=roledelegation#aws-integration-iam-policy
https://datadog-cloudformation-template.s3.amazonaws.com/aws/datadog_integration_role.yaml
```

Update the permissions (`statement.actions`) from those sources (you probably already did this, but please keep it exactly as on the website, except for whitespace):

<details><summary>full-integration permissions</summary>

```
  actions = [
    "apigateway:GET",
    "autoscaling:Describe*",
    "backup:List*",
    "budgets:ViewBudget",
    "cloudfront:GetDistributionConfig",
    "cloudfront:ListDistributions",
    "cloudtrail:DescribeTrails",
    "cloudtrail:GetTrailStatus",
    "cloudtrail:LookupEvents",
    "cloudwatch:Describe*",
    "cloudwatch:Get*",
    "cloudwatch:List*",
    "codedeploy:List*",
    "codedeploy:BatchGet*",
    "directconnect:Describe*",
    "dynamodb:List*",
    "dynamodb:Describe*",
    "ec2:Describe*",
    "ec2:GetTransitGatewayPrefixListReferences",
    "ec2:SearchTransitGatewayRoutes",
    "ecs:Describe*",
    "ecs:List*",
    "elasticache:Describe*",
    "elasticache:List*",
    "elasticfilesystem:DescribeFileSystems",
    "elasticfilesystem:DescribeTags",
    "elasticfilesystem:DescribeAccessPoints",
    "elasticloadbalancing:Describe*",
    "elasticmapreduce:List*",
    "elasticmapreduce:Describe*",
    "es:ListTags",
    "es:ListDomainNames",
    "es:DescribeElasticsearchDomains",
    "events:CreateEventBus",
    "fsx:DescribeFileSystems",
    "fsx:ListTagsForResource",
    "health:DescribeEvents",
    "health:DescribeEventDetails",
    "health:DescribeAffectedEntities",
    "kinesis:List*",
    "kinesis:Describe*",
    "lambda:GetPolicy",
    "lambda:List*",
    "logs:DeleteSubscriptionFilter",
    "logs:DescribeLogGroups",
    "logs:DescribeLogStreams",
    "logs:DescribeSubscriptionFilters",
    "logs:FilterLogEvents",
    "logs:PutSubscriptionFilter",
    "logs:TestMetricFilter",
    "oam:ListSinks",
    "oam:ListAttachedLinks",
    "organizations:Describe*",
    "organizations:List*",
    "rds:Describe*",
    "rds:List*",
    "redshift:DescribeClusters",
    "redshift:DescribeLoggingStatus",
    "route53:List*",
    "s3:GetBucketLogging",
    "s3:GetBucketLocation",
    "s3:GetBucketNotification",
    "s3:GetBucketTagging",
    "s3:ListAllMyBuckets",
    "s3:PutBucketNotification",
    "ses:Get*",
    "sns:List*",
    "sns:Publish",
    "sns:GetSubscriptionAttributes",
    "sqs:ListQueues",
    "states:ListStateMachines",
    "states:DescribeStateMachine",
    "support:DescribeTrustedAdvisor*",
    "support:RefreshTrustedAdvisorCheck",
    "tag:GetResources",
    "tag:GetTagKeys",
    "tag:GetTagValues",
    "wafv2:ListLoggingConfigurations",
    "wafv2:GetLoggingConfiguration",
    "xray:BatchGetTraces",
    "xray:GetTraceSummaries"
  ],
```

</details>

[ ] Rename  `iam_policy_core.tf` -> `iam-policy-core-integration.tf` and rename all the resources etc. named "core" to "core_integration", and trigger it with policy name "core-integration". 

Update [the policy reference](https://github.com/cloudposse/terraform-aws-datadog-integration/blob/d8b85a3a0484456022ae8a08c4ca8786cc64e40e/iam_policy_core.tf#L1) to 

```
https://datadog-cloudformation-template.s3.amazonaws.com/aws/datadog_integration_role.yaml
in the "else" clause of `!If GrantFullPermissions`
```

Update the permissions (`statement.actions`) by removing ['support:*'](https://github.com/cloudposse/terraform-aws-datadog-integration/blob/d8b85a3a0484456022ae8a08c4ca8786cc64e40e/iam_policy_core.tf#L14)


[ ] Create `iam-policy-resource-collection.tf`

Follow the pattern of `iam-policy-full-integration.tf` and create `iam-policy-resource-collection.tf` to implement the `resource-collection` option, referencing and using the policy from https://docs.datadoghq.com/integrations/amazon_web_services/?tab=roledelegation#aws-resource-collection-iam-policy-1

<details><summary>resource-collection permissions</summary>

```
  actions = [
    "backup:ListRecoveryPointsByBackupVault",
    "bcm-data-exports:GetExport",
    "bcm-data-exports:ListExports",
    "cassandra:Select",
    "cur:DescribeReportDefinitions",
    "ec2:GetSnapshotBlockPublicAccessState",
    "glacier:GetVaultNotifications",
    "glue:ListRegistries",
    "lightsail:GetInstancePortStates",
    "savingsplans:DescribeSavingsPlanRates",
    "savingsplans:DescribeSavingsPlans",
    "timestream:DescribeEndpoints",
    "waf-regional:ListRuleGroups",
    "waf-regional:ListRules",
    "waf:ListRuleGroups",
    "waf:ListRules",
    "wafv2:GetIPSet",
    "wafv2:GetRegexPatternSet",
    "wafv2:GetRuleGroup"
  ],
```

</details>

[ ] Create `iam-policy-SecurityAudit.tf`

Skip most of the content of the other files. I think it can be just

```hcl
locals {
  security_audit_count = local.enabled && 
    (contains(var.policies, "CSPM") || contains(var.policies, "SecurityAudit")) ? 1 : 0
}

resource "aws_iam_role_policy_attachment" "security_audit" {
  count      = local.security_audit_count
  role       = one(aws_iam_role.default[*].name)
  policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
}

2024-10-30 08:27 UTC, Nuru requested changes
See above

2024-11-05 23:59 UTC, StealthBadger747 commented
Just got caught up on my emails. @Nuru thanks for taking a look. I have personally deployed these changes in my workplace's environment at this point, but I would like to still see upstream changes.

At the moment I'm a bit busy with some other issues internally, but I will be working on a lot of Datadog things next week so I might be able to get to this then. It looks like I can implement these changes. I would also be happy to sync with @RoseSecurity if they might want to pick this up, or take more suggestions.

2025-01-30 19:18 UTC, StealthBadger747 commented
@RoseSecurity has picked this up

2025-01-30 19:18 UTC, closed without merging